[2023-10-07T02:13:52.869+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: read_db_by_mysql_hook_1.read_db manual__2023-10-07T01:56:44.184079+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-10-07T02:13:52.878+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
