[2023-10-07T04:21:49.767+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: dataframe_lab1.save_data scheduled__2023-10-06T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'change-datatype'}
[2023-10-07T04:21:49.774+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-10-07T04:21:52.673+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dataframe_lab1.save_data scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-07T04:21:52.680+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dataframe_lab1.save_data scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-07T04:21:52.681+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-10-07T04:21:52.693+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): save_data> on 2023-10-06 00:00:00+00:00
[2023-10-07T04:21:52.697+0000] {standard_task_runner.py:57} INFO - Started process 267 to run task
[2023-10-07T04:21:52.699+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dataframe_lab1', 'save_data', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/change_datatype.py', '--cfg-path', '/tmp/tmp9gw_adfo']
[2023-10-07T04:21:52.701+0000] {standard_task_runner.py:85} INFO - Job 113: Subtask save_data
[2023-10-07T04:21:52.735+0000] {task_command.py:415} INFO - Running <TaskInstance: dataframe_lab1.save_data scheduled__2023-10-06T00:00:00+00:00 [running]> on host ec1e187156c6
[2023-10-07T04:21:52.935+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dataframe_lab1' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-10-07T04:21:53.000+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-07T04:21:53.007+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dataframe_lab1, task_id=save_data, execution_date=20231006T000000, start_date=20231007T042152, end_date=20231007T042153
[2023-10-07T04:21:53.033+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-07T04:21:53.046+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
