[2023-10-26T10:14:12.298+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-24T00:00:00+00:00 [queued]>
[2023-10-26T10:14:12.306+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-24T00:00:00+00:00 [queued]>
[2023-10-26T10:14:12.307+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-10-26T10:14:12.317+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_db> on 2023-10-24 00:00:00+00:00
[2023-10-26T10:14:12.322+0000] {standard_task_runner.py:57} INFO - Started process 235 to run task
[2023-10-26T10:14:12.324+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'read_db_and_save_local', 'read_db', 'scheduled__2023-10-24T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/read_db_and_save_local.py', '--cfg-path', '/tmp/tmpnv22n328']
[2023-10-26T10:14:12.327+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask read_db
[2023-10-26T10:14:12.365+0000] {task_command.py:415} INFO - Running <TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-24T00:00:00+00:00 [running]> on host 88a410f69adf
[2023-10-26T10:14:12.540+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_db_and_save_local' AIRFLOW_CTX_TASK_ID='read_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-24T00:00:00+00:00'
[2023-10-26T10:14:12.548+0000] {base.py:73} INFO - Using connection ID 'mydb' for task execution.
[2023-10-26T10:14:12.556+0000] {logging_mixin.py:151} INFO - (('Danasawin', '19'),)
[2023-10-26T10:14:12.557+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-26T10:14:12.564+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=read_db_and_save_local, task_id=read_db, execution_date=20231024T000000, start_date=20231026T101412, end_date=20231026T101412
[2023-10-26T10:14:12.618+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-26T10:14:12.632+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
