[2023-10-26T10:14:04.160+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-25T00:00:00+00:00 [queued]>
[2023-10-26T10:14:04.170+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-25T00:00:00+00:00 [queued]>
[2023-10-26T10:14:04.171+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 3
[2023-10-26T10:14:04.181+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_db> on 2023-10-25 00:00:00+00:00
[2023-10-26T10:14:04.185+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2023-10-26T10:14:04.188+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'read_db_and_save_local', 'read_db', 'scheduled__2023-10-25T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/read_db_and_save_local.py', '--cfg-path', '/tmp/tmp5lne2vak']
[2023-10-26T10:14:04.191+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask read_db
[2023-10-26T10:14:04.229+0000] {task_command.py:415} INFO - Running <TaskInstance: read_db_and_save_local.read_db scheduled__2023-10-25T00:00:00+00:00 [running]> on host 88a410f69adf
[2023-10-26T10:14:04.415+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_db_and_save_local' AIRFLOW_CTX_TASK_ID='read_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-25T00:00:00+00:00'
[2023-10-26T10:14:04.422+0000] {base.py:73} INFO - Using connection ID 'mydb' for task execution.
[2023-10-26T10:14:04.432+0000] {logging_mixin.py:151} INFO - (('Danasawin', '19'),)
[2023-10-26T10:14:04.433+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-26T10:14:04.439+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=read_db_and_save_local, task_id=read_db, execution_date=20231025T000000, start_date=20231026T101404, end_date=20231026T101404
[2023-10-26T10:14:04.482+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-26T10:14:04.495+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
